# Generated by Django 3.1.7 on 2021-03-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=None, editable=False, help_text='创建时间', verbose_name='创建时间')),
                ('modified', models.DateTimeField(default=None, editable=False, help_text='更新时间', verbose_name='更新时间')),
                ('description', models.TextField(blank=True, default='', help_text='描述', verbose_name='描述')),
                ('name', models.CharField(help_text='名称', max_length=128, verbose_name='名称')),
                ('sn', models.CharField(help_text='编号', max_length=64, unique=True, verbose_name='编号')),
                ('level', models.IntegerField(choices=[(0, '紧急'), (1, '中等'), (2, '一般')], default=2, help_text="[(0, '紧急'), (1, '中等'), (2, '一般')]", verbose_name='级别')),
                ('current_state', models.IntegerField(choices=[(0, '打开'), (1, '定位中'), (2, '线上已恢复'), (3, '解决中'), (4, '上线中'), (5, '观察中'), (6, '结束')], default=0, help_text="[(0, '打开'), (1, '定位中'), (2, '线上已恢复'), (3, '解决中'), (4, '上线中'), (5, '观察中'), (6, '结束')]", verbose_name='当前状态')),
                ('current_operator', models.CharField(blank=True, default='', help_text='当前操作人', max_length=64, verbose_name='当前操作人')),
                ('related_resources', models.CharField(blank=True, default='', help_text='相关资源', max_length=512, verbose_name='相关资源')),
                ('occurrence_date', models.DateTimeField(help_text='发生时间', verbose_name='发生时间')),
            ],
            options={
                'verbose_name': '事件表',
                'verbose_name_plural': '事件表',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=None, editable=False, help_text='创建时间', verbose_name='创建时间')),
                ('modified', models.DateTimeField(default=None, editable=False, help_text='更新时间', verbose_name='更新时间')),
                ('description', models.TextField(blank=True, default='', help_text='描述', verbose_name='描述')),
                ('title', models.CharField(help_text='标题', max_length=256, verbose_name='标题')),
                ('state', models.IntegerField(choices=[(0, '打开'), (1, '定位中'), (2, '线上已恢复'), (3, '解决中'), (4, '上线中'), (5, '观察中'), (6, '结束')], default=0, help_text="[(0, '打开'), (1, '定位中'), (2, '线上已恢复'), (3, '解决中'), (4, '上线中'), (5, '观察中'), (6, '结束')]", verbose_name='当前状态')),
                ('current_operator', models.CharField(blank=True, default='', help_text='当前操作人', max_length=64, verbose_name='当前操作人')),
            ],
            options={
                'verbose_name': '事件记录表',
                'verbose_name_plural': '事件记录表',
            },
        ),
    ]
